### PR TITLE
Speed Reader and Synonym Improvements, Small Fixes

### PR DESCRIPTION
**Pull request by pacocoursey**
More pull requests for you! Getting annoying yet? :>

### Speed Reader

- Add small delay of 200ms before starting the speed reader
- Prevent speed reader initialization if too few words selected. This fixes a bug that prevents users from exiting the reader mode. Also early exit so it's (immeasurably) faster!
- ✨ Automatically scroll the text to the appropriate position when using the speed reader.

### Synonyms

- Correctly update the synonym index to wrap at end of array
- ✨ Improve the synonym selector behaviour so that you can actually see previously off-screen synonyms.

### Misc

- Add app icon to discard and close dialogs
- Fixed operator styling on mobile view

---

As always, let me know if there are any conflicting opinions about certain behaviors. Happy to rework!

### CODE REVIEW

**Comment by neauoire** [comment]
omg, it scrolls to the word!!!!

**Comment by neauoire** [comment]
that's so cool.

**Comment by neauoire** [comment]
Mhmm I'm having really weird scrolling behaviours on longer files.

**Comment by pacocoursey** [comment]
My mistake, it wants to start from the top of the document. You can revert these changes and I'll fix it and send a new pull request in the morning.

**Comment by pacocoursey** [comment]
Not sure of the "correct" GitHub way to make a small change for this but here's the 1 line fix you can commit yourself.

```js
// reader.js line 55

left.go.scroll_to(0, left.reader.segment.from + range);
```

**Pull request merged**
