### PR TITLE
Created tabs

### PR DESCRIPTION
**Pull request by ubiko**
Add tabs with `Ctrl/Cmd + T`
Delete tab with `Ctrl/Cmd + W`

I've added theme individuality (meaning one tab may be `blanc`, the other one `noir`).

Enjoy

### CODE REVIEW

**Comment by ubiko** [comment]
I got annoyed at constantly editing in and out the inspector, so I added environment variables.

Create a `.env` file in your root directory and add `NODE_ENV=development`.
This makes it so that it opens the inspector when doing `npm start` but not when building.

Also, i modified the package.json so you can run `npm run pack:osx` and auto build for OSX. Edit that to suit needs (like a more complex thing you've been doing in BUILD.md)

**Comment by ubiko** [comment]
The ID of the tabs don't re-organize themselves when you remove a tab. Need fix.

**Comment by ubiko** [comment]
My string replace killed `$` for the notes, add it to the exception i can't find them symbol for regex x_x

**Comment by neauoire** [comment]
Gimme a day or two to make sure this works on the chromebook as well :)

**Comment by neauoire** [comment]
The `pack:osx` thing is amazing, I had no idea you could do that.

**Comment by ubiko** [comment]
You can chain stuff up with `&&` too.

**Comment by neauoire** [comment]
I cannot merge this atm, but I've basically implemented this feature in project view :)

**Pull request closed without merging**
