### PR TITLE
 options update and optimizations

### PR DESCRIPTION
**Pull request by cantbesure1**
changes:
1. re-added theme option. The important part though is that you can dynamically load files from the theme folder using the syntax, not just the ones within the starting collection. (as a side note, in developing this I used the non-collection themes for the first time, and soyuz is really beautiful on windows)
2. fixed the double refresh bug
3. added actions syntax (really just goto, but inline. revolutionary)

I plan to re-add suggestion and synonym options with the new syntax and expand actions, but this pull request was already too big

### CODE REVIEW

**Comment by neauoire** [comment]
What do you mean by **actions syntax**?

**Comment by cantbesure1** [comment]
actions is just a name I gave to a subset of the options code that is responsible for one time events, like goto and (soon) word replacement. it was created as an inline alternative to the operator, as one of the things I initially fell in love with left for was how much was done in plain-text within the editor. So, for example, right now if you make a line with `> goto(1)` and press enter, the line will be deleted, and the cursor sent to the second line. However, if you feel this adds too much bloat to the application, I can remove it.

**Comment by neauoire** [comment]
Oh! that's amazing, I couldn't figure out how to use it. That should be in the readme!

**Comment by neauoire** [comment]
That's hardly bloat. ;)

**Pull request merged**
