### PR TITLE
Change font & font size

### PR DESCRIPTION
**Pull request by jrc03c**
I added the ability to toggle through fonts using ctrl+< and ctrl+>. As per issue #49, there are three fonts: Input Mono Regular, a serif, and a sans-serif. The serif and sans-serif fonts can be customized by replacing the serif.ttf and sans_serif.ttf files in the media/fonts folder. (Currently, they're [Zilla Slab](https://fonts.google.com/specimen/Zilla+Slab) and [Roboto Condensed](https://fonts.google.com/specimen/Roboto+Condensed).) The font size can also be increased with ctrl++, decreased with ctrl+-, and reset with ctrl+).

### CODE REVIEW

**Comment by pacocoursey** [comment]
Remember that Left is now using the Standard style guide. Run `npm run lint` to view any errors.

I played with this idea a while back and found bugs with the reader mode. Because the reader mode basically inserts and quickly removes a `div` element so it knows when to scroll to, ensure that the CSS rule for `body div` reflects any changes in font-size and line-height (otherwise the inserted div will be the wrong height, and the reader mode will eventually become misaligned with the text).

I'd also change the keybind to show <kbd>Cmd+Shift+.</kbd> rather than <kbd>Cmd+></kbd>, as the latter makes me want to press <kbd>Cmd+.</kbd>. Just my opinion though. Also, I think the decrease font size shortcut is <kbd>Cmd+Shift+-</kbd> right now, instead of the desired <kbd>Cmd+-</kbd>. And it's more common to use <kbd>Cmd+0</kbd> to reset the size, without the shift modifier.

The menu ordering also feels a bit off, maybe a new section for "Font" works better than splitting the options between "View" and "Theme".

Nice work!

**Comment by jrc03c** [comment]
@pacocoursey Thanks for the notes. I hadn't known about the style guide, and I didn't even think to check the line-height problem. I've sorted out the other things, I think, but the line-height is still being a pain. :(

**Comment by jrc03c** [comment]
@pacocoursey Thanks for the PR!

**Comment by neauoire** [comment]
I'm currently away from the computer while we re-stock.
I'll check the PR when I get back :) Sorry

**Comment by neauoire** [comment]
This is incredible.

**Pull request merged**
