### PR TITLE
Scroll to Header or Note

### PR DESCRIPTION
**Pull request by ubiko**
I was annoyed that selecting on the left wouldn't scroll to it, so I added it.

I think the offset is off...but that's a start.

### CODE REVIEW

**Comment by ubiko** [comment]
Added two new themes. ;)

**Comment by ubiko** [comment]
Compressed Image of the Blur Theme: 
Compressed Image of the Blur Theme

**Comment by ubiko** [comment]
So I was only doing `electron .` up until then, when I tried to build it I actually had to regress to electron-packager `1.4.5`.

I don't know why it wouldn't let me in `1.7.5` but it should allow me to, must be something regarding my NodeJS version.

**Comment by neauoire** [comment]
Punk is too much of a mess, and doesn't work too well on my end, I ll remove these changes for now.

**Comment by neauoire** [comment]
But thanks for the go_to fixes :) I'll try to build onto that.

**Comment by ubiko** [comment]
@neauoire yeah i was gonna say, it's not working well when switching themes. Hopefully you were able to see it though.

I think it one of the issue it has is how the theme is recognized. If you look at the body class it's actually registering as

```
<body class="noir               

$ Note">...
```

Maybe instead of grabbing directly from input->body class have whatever is being recognized as a theme to be stored in an array, this way you could eventually do sub-themes.

Input->AddToArray->ArrayToClass

This way you could do something like
`body.noir.blur`
`body.blanc.blur`


Just an idea. @neauoire

**Pull request merged**
